language: go

go:
  - 1.x

install:
  - "go get github.com/gorilla/mux"
  - "go get golang.org/x/crypto/bcrypt"
  - "go get github.com/lib/pq"
  - "go get github.com/paulkramme/toml"

script:
  - go build
